provider "openstack" {
  region  = "${var.tectonic_openstack_region}"
  version = ">=1.6.0"

  auth_url = "${var.tectonic_openstack_credentials_auth_url}"
  cloud = "${var.tectonic_openstack_credentials_cloud}"
  region = "${var.tectonic_openstack_credentials_region}"
  user_name = "${var.tectonic_openstack_credentials_user_name}"
  user_id = "${var.tectonic_openstack_credentials_user_id}"
  tenant_id = "${var.tectonic_openstack_credentials_tenant_id}"
  tenant_name = "${var.tectonic_openstack_credentials_tenant_name}"
  password = "${var.tectonic_openstack_credentials_password}"
  token = "${var.tectonic_openstack_credentials_token}"
  user_domain_name = "${var.tectonic_openstack_credentials_user_domain_name}"
  user_domain_id = "${var.tectonic_openstack_credentials_user_domain_id}"
  project_domain_name = "${var.tectonic_openstack_credentials_project_domain_name}"
  project_domain_id = "${var.tectonic_openstack_credentials_project_domain_id}"
  domain_id = "${var.tectonic_openstack_credentials_domain_id}"
  domain_name = "${var.tectonic_openstack_credentials_domain_name}"
  insecure = "${var.tectonic_openstack_credentials_insecure}"
  cacert_file = "${var.tectonic_openstack_credentials_cacert_file}"
  cert = "${var.tectonic_openstack_credentials_cert}"
  key = "${var.tectonic_openstack_credentials_key}"
  endpoint_type = "${var.tectonic_openstack_credentials_endpoint_type}"
  swauth = "${var.tectonic_openstack_credentials_swauth}"
  use_octavia = "${var.tectonic_openstack_credentials_use_octavia}"
}
