ignored = ["github.com/openshift/installer/tests*"]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.6.2"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.39"

[[constraint]]
  name = "github.com/coreos/ignition"
  version = "0.26.0"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/tectonic-config"

[[constraint]]
  name = "github.com/libvirt/libvirt-go"
  version = "4.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/vfsgen"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/vincent-petithory/dataurl"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"
